### ISSUE TITLE
SystemWipe Script does not work

### ISSUE THREAD

**Issue by muxi1** [suchmememanyskill/TegraExplorer#93] opened 2024-03-30 15:57 UTC
When I try to reset my emuMMC, this error message appears:

**[FATAL] Variable ´getfilesize´ not found
Error occured on or near line 28** 

To be on the safe side, I had previously created a backup of the emuMMC partition to fix the resulting brick.

**Comment by suchmememanyskill** [comment] 2024-03-30 16:01
It sounds like you're using the newer systemwipe script with the current release of tegraexplorer. This doesn't work. You need the latest build of TE

**Comment by muxi1** [comment] 2024-03-30 16:05
Yeah, you're right. I'm still using the official release. Sorry for the inconvenience.

**Comment by muxi1** [comment] 2024-03-30 18:17
Does the change solve the problem with the SemiBrick, which was previously solved by booting Fusee?

Edit:
I have now compiled the latest build and successfully applied the SystemWipe script. However, there still seems to be a brick of the nand in question.

**Comment by suchmememanyskill** [comment] 2024-03-30 19:38
@JeffVi made the feature, it should solve the bricking on 17.x+

**Comment by muxi1** [comment] 2024-03-30 19:44
I'm on FW version 18.0.0 with sysmmc & emuMMC, but the SystemWipe script doesn't seem to work (even on the latest TE build, where it runs flawlessly) because it always bricks the nand on which it is applied. Something is wrong with it....

**Comment by gabrieluto** [comment] 2024-04-18 16:29
I accidentally restored my emunand's backup onto my sysnand, realized before the process finished, did a SystemWipe.te from the latest release; on boot the console shows the nintendo logo and that's it, tried using the build from the merged branch, and still got the same result, I was on FW 18.0, so I can confirm the mentioned behavior.

**Comment by suchmememanyskill** [comment] 2024-04-18 17:12
@gabrieluto for now until we find a fix you'd need to boot at least once with atmosphere

**Comment by Dyl-Aeon** [comment] 2024-04-20 00:34
DISREGARD. I decided since it was frozen, no harm in forcing shutdown.
Boots normally to 'stock'.

Might try factory resetting from within stock firmware, see if that accomplishes what I was trying to do.


```
I'm on OFW 11.0.1, unpatched v1 Switch.
![image](https://github.com/suchmememanyskill/TegraExplorer/assets/55271102/c1e107f7-a334-445b-8370-761b99d49ea5)
Just attempted to clean my sysmmc with 4.1.1
Selected sysmmc, and then... stuck. No progress.

How long does this typically take? Afraid to interrupt it. More afraid it's too late.

I'm stuck here. Not sure if I should force power off or if it doesn't matter anymore.
Previously was using SXOS, Switch was purchased secondhand on OFW 10.2? Can't recall. I do remember using ChoiDujourNX to upgrade to 11.0.1. Was unsure if CFW had touched sysnand or not.

Recently was looking to migrate to Atmosphere, but that meant giving up .XCI's. As I tried to sort out the .NSP decryption, I realized something was wrong with my BISKEY dump(s). Entropy like:
![image](https://github.com/suchmememanyskill/TegraExplorer/assets/55271102/61bd0ef2-65e9-4db0-a86e-71d65b8fc893)
I couldn't make heads or tails of what to do next. Most guides detailing this are coming from a total NAND rebuild. Meanwhile, I could still boot into stock. I figured a factory reset would create new BISKEYs for the user partition (surely?).
```

**Comment by UeEiFetischist** [comment] 2024-05-02 06:49
I have similar problems.
I was on 18.0 with my OFW before I modded my OLED. Now my CFW with emummc is running but not my OFW.
With my OFW I get stuck at the Nintendo logo.
So I tried to reset the FW with SystemWipe, but as soon as I try to run it I get an error 21 in line 111 file: source/storage/gptmenu.c keydump failed.
I am using tegraexplorer 4.1.1.
I have seen here that there is a new version of the script, but I don't know how to copy it to my switch, as the current build is still from October 2023.

**Comment by muxi1** [comment] 2024-05-02 06:56
@UeEiFetischist You must compile the current code to avoid this error message. But the systemwipe script would still not work. It still needs a fix.

**Comment by suchmememanyskill** [comment] 2024-05-02 07:11
> I have similar problems.
> I was on 18.0 with my OFW before I modded my OLED. Now my CFW with emummc is running but not my OFW.
> With my OFW I get stuck at the Nintendo logo.
> So I tried to reset the FW with SystemWipe, but as soon as I try to run it I get an error 21 in line 111 file: source/storage/gptmenu.c keydump failed.
> I am using tegraexplorer 4.1.1.
> I have seen here that there is a new version of the script, but I don't know how to copy it to my switch, as the current build is still from October 2023.

I doubt a systemwipe would fix your issue. But your issue isn't related to this thread; you didn't dump your keys

**Comment by urherenow** [comment] 2024-05-03 17:13
> @UeEiFetischist You must compile the current code to avoid this error message. But the systemwipe script would still not work. It still needs a fix.

but compiling the current code in ubuntu, with all of the dkp libraries up to date, spits out a warning that the payload is too large, and neither of the produced payloads will load. black screen and a requirement to force-shutdown. This is on an OLED.

**Comment by CrazyNInja485** [comment] 2024-05-31 21:47
> У меня похожие проблемы. Я был на 18.0 с моим OFW до того, как модифицировал свой OLED. Теперь мой CFW с emummc запущен, но не мой OFW. С моим OFW я застреваю на логотипе Nintendo. Итак, я попытался сбросить FW с помощью SystemWipe, но как только я пытаюсь его запустить, я получаю ошибку 21 в строке 111 файл: source / storage / gptmenu.c сбой сброса ключа. Я использую tegraexplorer 4.1.1. Я видел здесь, что есть новая версия скрипта, но я не знаю, как скопировать ее на мой коммутатор, поскольку текущая сборка все еще датирована октябрем 2023 года.

hi, I have the same problem after all, I'm not the only one. So have you solved it or not?

**Comment by suchmememanyskill** [comment] 2024-05-31 21:56
I'm closing this issue. The original post talks about an unreleased feature. This has completely derailed at this point

**Closed as completed by suchmememanyskill** 2024-05-31 21:56 UTC
